sudo: required
language: go
services:
  - docker
go:
- 1.8.x
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
- echo "test skip"

deploy:
  - provider: script
    script: IMAGE_LABLE=$TRAVIS_BRANCH make publish
    on:
      tags: true

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker login -u="$QING_DOCKER_USER" -p="$QING_DOCKER_PASSWD" dockerhub.qingcloud.com
  - IMAGE_LABLE=$TRAVIS_BRANCH make install-docker