apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    component: cloud-controller-manager
    tier: control-plane
  name: cloud-controller-manager
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/qingcloud-cloud-controller-manager
    - --v=${KUBE_LOG_LEVEL}
    - --cloud-provider=qingcloud
    - --cloud-config=/etc/kubernetes/qingcloud.conf
    - --kubeconfig=/etc/kubernetes/admin.conf
    - --allocate-node-cidrs=true
    - --cluster-cidr=10.244.0.0/16
    - --use-service-account-credentials=false
    - --feature-gates=AllAlpha=true,DynamicKubeletConfig=false,RotateKubeletServerCertificate=false,RotateKubeletClientCertificate=false
    image: dockerhub.qingcloud.com/qingcloud/qingcloud-cloud-controller-manager:v1.1.2
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10253
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: qingcloud-cloud-controller-manager
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: k8s
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: certs
    - mountPath: /etc/qingcloud
      name: qingcloud
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: k8s
  - hostPath:
      path: /etc/ssl/certs
    name: certs
  - hostPath:
      path: /etc/qingcloud
    name: qingcloud

